version: '3.9'

services:
  back-end:
    build:
      context: './gotham'
    command: sh -c 'mix ecto.setup && mix phx.server'
    working_dir: /app
    container_name: 'back-end'
    restart: 'unless-stopped'
    volumes:
      - "./gotham:/app"
    environment:
      - 'DATABASE_URL=ecto://postgres:postgres@postgres-db:5432/gotham_dev'
    depends_on:
      - 'postgres-db'
    ports:
      - '4000:4000'
    networks:
      - backend

  postgres-db:
    image: 'postgres:15.0-alpine'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
    networks:
      - backend

  front-end:
    build:
      context: './gotham-front'
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    container_name: 'front-end'
    volumes:
      - "./gotham-front:/app"
    environment:
      - 'VITE_BACKEND_URL=http://localhost:4000'
    ports:
      - '5173:5173'
    depends_on:
      - 'back-end'
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend: