version: '3.9'

services:
  back-end:
    image: '850194915763.dkr.ecr.eu-west-3.amazonaws.com/gotham-back:latest'
    # build:
    #   context: './gotham'
    command: sh -c 'mix local.rebar --force && mix ecto.setup && mix phx.server'
    container_name: 'back-end'
    restart: 'unless-stopped'
    environment:
      - 'DATABASE_URL=ecto://postgres:postgres@postgres-db:5432/gotham_dev'
    depends_on:
      - 'postgres-db'
    ports:
      - '4000:4000'
    networks:
      - backend

  postgres-db:
    image: 'postgres:15.0-alpine'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
    networks:
      - backend

  front-end:
    image: '850194915763.dkr.ecr.eu-west-3.amazonaws.com/gotham-front:latest'
    # build:
      # context: './gotham-front'
    command: sh -c 'npm run dev'
    container_name: 'front-end'
    environment:
      - 'VITE_BACKEND_URL=http://35.180.192.245:4000'
    ports:
      - '5173:5173'
    depends_on:
      - 'back-end'
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend: