name: Build and test

on: push
  
jobs:
  test:
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
    steps:
      - name: go into back-end folder
        run: cd gotham
      - name: execute tests
        run: mix test