# name: Build and test

# on: push
  
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       db:
#         image: 'postgres:15.0-alpine'
#         ports: ['5432:5432']
#         env:
#           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup elixir
#         uses: actions/setup-elixir@v1
#         with:
#           otp-version: '25'
#           elixir-version: '1.14.1'
#       - name: Install Dependencies
#         run: mix deps.get
#       - name: Run Tests
#         run: mix test


name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    name: Build and test
    runs-on: ubuntu-latest
    services:
      db:
        image: 'postgres:15.0-alpine'
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.14.1' # Define the elixir version [required]
        otp-version: '25' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      working-directory: ./gotham
      run: mix deps.get
    - name: Run tests
      working-directory: ./gotham
      run: mix test
