name: Build and test

on: push
  
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: 'postgres:15.0-alpine'
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.14.1'
      - run: mix deps.get
      - run: mix test